---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List Files for Debugging
        run: ls -la weathet_app

      - name: Install Dependencies
        run: npm install --prefix weathet_app

      - name: Run Application
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cd weathet_app
          npm start
